@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>GameHelper</b>\n<size:10>soen6441riskgame.utils" as soen6441riskgame.utils.GameHelper  [[../../soen6441riskgame/utils/GameHelper.html{soen6441riskgame.utils.GameHelper}]] {
+GameHelper()
{static} +int rollDice()
{static} +int getMax(int inputArray,boolean secondMax)
{static} +int nextRandomIntInRange(int min,int max)
{static} +int nextRandomInt(int max)
{static} +ArrayList<Integer> getRandomElements(ArrayList<Integer> list,int totalItems)
{static} +List<K> getAllKeysForValue(Map<K, V> maps,Object value)
{static} +int countDistinct(Object array)
}




class "<b><size:14>Object</b>\n<size:10>java.lang" as java.lang.Object  #lightgrey {
}

hide java.lang.Object fields
hide java.lang.Object methods

soen6441riskgame.utils.GameHelper ..> java.lang.Object



@enduml
