@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>GameController</b>\n<size:10>soen6441riskgame.controllers" as soen6441riskgame.controllers.GameController  [[../../soen6441riskgame/controllers/GameController.html{soen6441riskgame.controllers.GameController}]] {
{static} -int NUMBER_OF_CARD_IN_ONE_SET
{static} -int MAXIMUM_ARMY_IN_ONE_ATTACK
{static} -int MINIMUM_ARMY_TO_ATTACK
{static} -int MINIMUM_NUMBER_OF_PLAYER
{static} -int MAXIMUM_NUMBER_OF_PLAYER
{static} -int MINIMUM_NUMBER_OF_ARMY_ON_COUNTRY
+GameController()
+void handleGamePlayerCommand(String args)
+boolean isNumberOfPlayerValid()
+void populateCountries()
+void initPlayersUnplacedArmies()
+void handlePlaceArmyCommand(String countryName)
+void handlePlaceAllCommand()
+Player getCurrentPlayer()
+Player startRoundRobinPlayers()
+void showCurrentPlayer()
+boolean enterReinforcement()
+void handleReinforceCommand(String args)
+boolean enterFortifyPhase()
+void handleMultipleFortificationCommand(String args)
+boolean enterAttackPhase()
+void handleAttackCommand(String args)
+void handleDefendCommand(String args)
+void handleAttackMoveCommand(String args)
+void exchangeCard(String args)
~void turnToNextPlayer()
~boolean isAttackValid(Country attackingCountry,int attackerNumDice,int defenderNumDice,boolean alloutFlag)
~void setEndOfGamePhase()
-Player getCurrentPlayer(boolean isShowMessage)
-void handleFortifyCommand(String args)
-void simulateAttack(GameBoardPlaying gameBoardPlaying)
-boolean isGameEnded()
-boolean isAttackPreconditionsValid(Country attackingCountry,Country defendingCountry)
-void attackResult(Country defendingCountry,Country attackingCountry)
-void endAttackPhase()
-CardSet buildCardSet(String args)
}


class "<b><size:14>Player</b>\n<size:10>soen6441riskgame.models" as soen6441riskgame.models.Player  [[../../soen6441riskgame/models/Player.html{soen6441riskgame.models.Player}]] #white {
}

hide soen6441riskgame.models.Player fields
hide soen6441riskgame.models.Player methods

soen6441riskgame.controllers.GameController ..> soen6441riskgame.models.Player




class "<b><size:14>TournamentController</b>\n<size:10>soen6441riskgame.controllers" as soen6441riskgame.controllers.TournamentController  [[../../soen6441riskgame/controllers/TournamentController.html{soen6441riskgame.controllers.TournamentController}]] {
}

hide soen6441riskgame.controllers.TournamentController fields
hide soen6441riskgame.controllers.TournamentController methods

soen6441riskgame.controllers.TournamentController -->  "gameController" soen6441riskgame.controllers.GameController


@enduml
