@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>MapController</b>\n<size:10>soen6441riskgame.controllers" as soen6441riskgame.controllers.MapController  [[../../soen6441riskgame/controllers/MapController.html{soen6441riskgame.controllers.MapController}]] {
{static} -int MINIMUM_AMOUNT_OF_COUNTRIES
-DominationMapReadable dominationMapReader
-ConquestMapReadable conquestMapReader
+MapController()
+void loadMap(String fileName,boolean isConquestMapType)
+void loadMap(String fileName)
+void addContinent(String continentName,String continentValue,int order)
+void addCountry(String countryName,String continentName)
+void addNeighbor(String countryName,String neighborCountryName)
+void createNewCountry(String countryName,Continent continent)
+void editContinent(String args)
+void editCountry(String args)
+void editMap(String fileName)
+void saveMap(String fileName,boolean isConquestMapType)
+void saveMap(String fileName)
+void editNeighbor(String args)
+void removeContinent(String continentName)
+void removeCountry(String countryName)
+void removeNeighbor(String countryName,String neighborCountryName)
+void showMap()
+boolean isMapValid()
+void validateMap()
-void increaseBorder(int newBorderSize)
-ArrayList<Continent> getEmptyContinents()
-ArrayList<Country> getIsolatedCountries()
-boolean isNotEnoughCountries()
-void removeBorder(int borderLocation)
-ArrayList<Country> getCountriesHaveNoContinent()
}


interface "<b><size:14>DominationMapReadable</b>\n<size:10>soen6441riskgame.utils.map" as soen6441riskgame.utils.map.DominationMapReadable  [[../../soen6441riskgame/utils/map/DominationMapReadable.html{soen6441riskgame.utils.map.DominationMapReadable}]] #white {
}

hide soen6441riskgame.utils.map.DominationMapReadable fields
hide soen6441riskgame.utils.map.DominationMapReadable methods

soen6441riskgame.controllers.MapController -->  "dominationMapReader" soen6441riskgame.utils.map.DominationMapReadable

interface "<b><size:14>ConquestMapReadable</b>\n<size:10>soen6441riskgame.utils.map" as soen6441riskgame.utils.map.ConquestMapReadable  [[../../soen6441riskgame/utils/map/ConquestMapReadable.html{soen6441riskgame.utils.map.ConquestMapReadable}]] #white {
}

hide soen6441riskgame.utils.map.ConquestMapReadable fields
hide soen6441riskgame.utils.map.ConquestMapReadable methods

soen6441riskgame.controllers.MapController -->  "conquestMapReader" soen6441riskgame.utils.map.ConquestMapReadable

class "<b><size:14>Continent</b>\n<size:10>soen6441riskgame.models" as soen6441riskgame.models.Continent  [[../../soen6441riskgame/models/Continent.html{soen6441riskgame.models.Continent}]] #white {
}

hide soen6441riskgame.models.Continent fields
hide soen6441riskgame.models.Continent methods

soen6441riskgame.controllers.MapController ..> soen6441riskgame.models.Continent



class "<b><size:14>Country</b>\n<size:10>soen6441riskgame.models" as soen6441riskgame.models.Country  [[../../soen6441riskgame/models/Country.html{soen6441riskgame.models.Country}]] #white {
}

hide soen6441riskgame.models.Country fields
hide soen6441riskgame.models.Country methods

soen6441riskgame.controllers.MapController ..> soen6441riskgame.models.Country


@enduml
