@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>SaveLoadController</b>\n<size:10>soen6441riskgame.controllers" as soen6441riskgame.controllers.SaveLoadController  [[../../soen6441riskgame/controllers/SaveLoadController.html{soen6441riskgame.controllers.SaveLoadController}]] {
+SaveLoadController()
+boolean saveGame(String saveGameFilePath)
+boolean loadGame(String savedGameFilePath)
-void deserialize(JsonReader reader)
}




@enduml
