@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>ArrayNameOnlyJsonAdapter</b>\n<size:10>soen6441riskgame.models.serializers" as soen6441riskgame.models.serializers.ArrayNameOnlyJsonAdapter  [[../../../soen6441riskgame/models/serializers/ArrayNameOnlyJsonAdapter.html{soen6441riskgame.models.serializers.ArrayNameOnlyJsonAdapter}]] {
+ArrayNameOnlyJsonAdapter()
+void write(JsonWriter out,ArrayList<NameOnlySerializable> value)
+ArrayList<NameOnlySerializable> read(JsonReader in)
}


class "<b><size:14>TypeAdapter<ArrayList></b>\n<size:10>com.google.gson" as com.google.gson.TypeAdapterArrayList<NameOnlySerializable>  #lightgrey {
}

hide com.google.gson.TypeAdapterArrayList<NameOnlySerializable> fields
hide com.google.gson.TypeAdapterArrayList<NameOnlySerializable> methods

soen6441riskgame.models.serializers.ArrayNameOnlyJsonAdapter --|> com.google.gson.TypeAdapterArrayList<NameOnlySerializable>


class "<b><size:14>JsonWriter</b>\n<size:10>com.google.gson.stream" as com.google.gson.stream.JsonWriter  #lightgrey {
}

hide com.google.gson.stream.JsonWriter fields
hide com.google.gson.stream.JsonWriter methods

soen6441riskgame.models.serializers.ArrayNameOnlyJsonAdapter ..> com.google.gson.stream.JsonWriter

class "<b><size:14>NameOnlySerializable</b>\n<size:10>soen6441riskgame.models.serializers" as soen6441riskgame.models.serializers.NameOnlySerializable  [[../../../soen6441riskgame/models/serializers/NameOnlySerializable.html{soen6441riskgame.models.serializers.NameOnlySerializable}]] {
}

hide soen6441riskgame.models.serializers.NameOnlySerializable fields
hide soen6441riskgame.models.serializers.NameOnlySerializable methods

soen6441riskgame.models.serializers.ArrayNameOnlyJsonAdapter ..> soen6441riskgame.models.serializers.NameOnlySerializable

class "<b><size:14>JsonReader</b>\n<size:10>com.google.gson.stream" as com.google.gson.stream.JsonReader  #lightgrey {
}

hide com.google.gson.stream.JsonReader fields
hide com.google.gson.stream.JsonReader methods

soen6441riskgame.models.serializers.ArrayNameOnlyJsonAdapter ..> com.google.gson.stream.JsonReader


@enduml
