@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
package soen6441riskgame.models.serializers [[../../../soen6441riskgame/models/serializers/package-summary.html{soen6441riskgame.models.serializers}]] #lightyellow {
}

class "<b><size:14>SerializableGame</b>" as soen6441riskgame.models.serializers.SerializableGame  [[../../../soen6441riskgame/models/serializers/SerializableGame.html{soen6441riskgame.models.serializers.SerializableGame}]] {
}

hide soen6441riskgame.models.serializers.SerializableGame fields
hide soen6441riskgame.models.serializers.SerializableGame methods

class "<b><size:14>SerializableGame.Builder</b>" as soen6441riskgame.models.serializers.SerializableGame.Builder  [[../../../soen6441riskgame/models/serializers/SerializableGame.Builder.html{soen6441riskgame.models.serializers.SerializableGame.Builder}]] {
}

hide soen6441riskgame.models.serializers.SerializableGame.Builder fields
hide soen6441riskgame.models.serializers.SerializableGame.Builder methods

soen6441riskgame.models.serializers.SerializableGame.Builder ..> soen6441riskgame.models.serializers.SerializableGame

@enduml
