@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>SerializableGame.Builder</b>\n<size:10>soen6441riskgame.models.serializers" as soen6441riskgame.models.serializers.SerializableGame.Builder  [[../../../soen6441riskgame/models/serializers/SerializableGame.Builder.html{soen6441riskgame.models.serializers.SerializableGame.Builder}]] {
-ArrayList<Country> countries
-ArrayList<Continent> continents
-ArrayList<Player> players
-int borders
-Card cards
+Builder()
+SerializableGame.Builder setContinents(ArrayList<Continent> continents)
+SerializableGame.Builder setCountries(ArrayList<Country> countries)
+SerializableGame.Builder setPlayers(ArrayList<Player> players)
+SerializableGame.Builder setBorders(int borders)
+SerializableGame.Builder setCards(Card cards)
+SerializableGame build()
}



class "<b><size:14>Country</b>\n<size:10>soen6441riskgame.models" as soen6441riskgame.models.Country  [[../../../soen6441riskgame/models/Country.html{soen6441riskgame.models.Country}]] #white {
}

hide soen6441riskgame.models.Country fields
hide soen6441riskgame.models.Country methods

soen6441riskgame.models.serializers.SerializableGame.Builder ..> soen6441riskgame.models.Country


class "<b><size:14>Continent</b>\n<size:10>soen6441riskgame.models" as soen6441riskgame.models.Continent  [[../../../soen6441riskgame/models/Continent.html{soen6441riskgame.models.Continent}]] #white {
}

hide soen6441riskgame.models.Continent fields
hide soen6441riskgame.models.Continent methods

soen6441riskgame.models.serializers.SerializableGame.Builder ..> soen6441riskgame.models.Continent


class "<b><size:14>Player</b>\n<size:10>soen6441riskgame.models" as soen6441riskgame.models.Player  [[../../../soen6441riskgame/models/Player.html{soen6441riskgame.models.Player}]] #white {
}

hide soen6441riskgame.models.Player fields
hide soen6441riskgame.models.Player methods

soen6441riskgame.models.serializers.SerializableGame.Builder ..> soen6441riskgame.models.Player

class "<b><size:14>Card</b>\n<size:10>soen6441riskgame.models" as soen6441riskgame.models.Card  [[../../../soen6441riskgame/models/Card.html{soen6441riskgame.models.Card}]] #white {
}

hide soen6441riskgame.models.Card fields
hide soen6441riskgame.models.Card methods

soen6441riskgame.models.serializers.SerializableGame.Builder -->  "cards" soen6441riskgame.models.Card

class "<b><size:14>SerializableGame</b>\n<size:10>soen6441riskgame.models.serializers" as soen6441riskgame.models.serializers.SerializableGame  [[../../../soen6441riskgame/models/serializers/SerializableGame.html{soen6441riskgame.models.serializers.SerializableGame}]] {
}

hide soen6441riskgame.models.serializers.SerializableGame fields
hide soen6441riskgame.models.serializers.SerializableGame methods

soen6441riskgame.models.serializers.SerializableGame.Builder ..> soen6441riskgame.models.serializers.SerializableGame


@enduml
