@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>GameBoard</b>\n<size:10>soen6441riskgame.singleton" as soen6441riskgame.singleton.GameBoard  [[../../soen6441riskgame/singleton/GameBoard.html{soen6441riskgame.singleton.GameBoard}]] {
+PrintStream standardPrintStream
{static} -int NUMBER_OF_CARDS
{static} -GameBoard instance
-GameBoardPlayer gameBoardPlayer
-GameBoardMap gameBoardMap
-GameBoardPlaying gameBoardPlaying
-ExchangeCardView exchangeCardView
-Card cards
+GameBoard()
+void initCards()
+Card getSpecificCardForTest(CardType cardType)
+Card getCardsForSave()
+void loadCardFromSave(Card cards)
+void loadGameBoardPlaying(GameBoardPlaying serialized)
+Card getRandomAvailableCard()
+ExchangeCardView getExchangeCardView()
+GameBoardPlayer getGameBoardPlayer()
+GameBoardMap getGameBoardMap()
+GameBoardPlaying getGameBoardPlaying()
{static} +void setTestingInstance(GameBoard newTestingInstance)
{static} +GameBoard getInstance()
+void reset()
}


class "<b><size:14>AggressiveStrategy</b>\n<size:10>soen6441riskgame.models.strategies" as soen6441riskgame.models.strategies.AggressiveStrategy  [[../../soen6441riskgame/models/strategies/AggressiveStrategy.html{soen6441riskgame.models.strategies.AggressiveStrategy}]] #white {
}

hide soen6441riskgame.models.strategies.AggressiveStrategy fields
hide soen6441riskgame.models.strategies.AggressiveStrategy methods

soen6441riskgame.models.strategies.AggressiveStrategy ..> soen6441riskgame.singleton.GameBoard

class "<b><size:14>BenevolentStrategy</b>\n<size:10>soen6441riskgame.models.strategies" as soen6441riskgame.models.strategies.BenevolentStrategy  [[../../soen6441riskgame/models/strategies/BenevolentStrategy.html{soen6441riskgame.models.strategies.BenevolentStrategy}]] #white {
}

hide soen6441riskgame.models.strategies.BenevolentStrategy fields
hide soen6441riskgame.models.strategies.BenevolentStrategy methods

soen6441riskgame.models.strategies.BenevolentStrategy ..> soen6441riskgame.singleton.GameBoard

interface "<b><size:14>IStrategy</b>\n<size:10>soen6441riskgame.models.strategies" as soen6441riskgame.models.strategies.IStrategy  [[../../soen6441riskgame/models/strategies/IStrategy.html{soen6441riskgame.models.strategies.IStrategy}]] #white {
}

hide soen6441riskgame.models.strategies.IStrategy fields
hide soen6441riskgame.models.strategies.IStrategy methods

soen6441riskgame.models.strategies.IStrategy ..> soen6441riskgame.singleton.GameBoard

class "<b><size:14>RandomStrategy</b>\n<size:10>soen6441riskgame.models.strategies" as soen6441riskgame.models.strategies.RandomStrategy  [[../../soen6441riskgame/models/strategies/RandomStrategy.html{soen6441riskgame.models.strategies.RandomStrategy}]] #white {
}

hide soen6441riskgame.models.strategies.RandomStrategy fields
hide soen6441riskgame.models.strategies.RandomStrategy methods

soen6441riskgame.models.strategies.RandomStrategy ..> soen6441riskgame.singleton.GameBoard

soen6441riskgame.singleton.GameBoard -->  "instance" soen6441riskgame.singleton.GameBoard

class "<b><size:14>GameBoardPlayer</b>\n<size:10>soen6441riskgame.singleton" as soen6441riskgame.singleton.GameBoardPlayer  [[../../soen6441riskgame/singleton/GameBoardPlayer.html{soen6441riskgame.singleton.GameBoardPlayer}]] {
}

hide soen6441riskgame.singleton.GameBoardPlayer fields
hide soen6441riskgame.singleton.GameBoardPlayer methods

soen6441riskgame.singleton.GameBoard -->  "gameBoardPlayer" soen6441riskgame.singleton.GameBoardPlayer

class "<b><size:14>GameBoardMap</b>\n<size:10>soen6441riskgame.singleton" as soen6441riskgame.singleton.GameBoardMap  [[../../soen6441riskgame/singleton/GameBoardMap.html{soen6441riskgame.singleton.GameBoardMap}]] {
}

hide soen6441riskgame.singleton.GameBoardMap fields
hide soen6441riskgame.singleton.GameBoardMap methods

soen6441riskgame.singleton.GameBoard -->  "gameBoardMap" soen6441riskgame.singleton.GameBoardMap

class "<b><size:14>GameBoardPlaying</b>\n<size:10>soen6441riskgame.singleton" as soen6441riskgame.singleton.GameBoardPlaying  [[../../soen6441riskgame/singleton/GameBoardPlaying.html{soen6441riskgame.singleton.GameBoardPlaying}]] {
}

hide soen6441riskgame.singleton.GameBoardPlaying fields
hide soen6441riskgame.singleton.GameBoardPlaying methods

soen6441riskgame.singleton.GameBoard -->  "gameBoardPlaying" soen6441riskgame.singleton.GameBoardPlaying

class "<b><size:14>ExchangeCardView</b>\n<size:10>soen6441riskgame.views" as soen6441riskgame.views.ExchangeCardView  [[../../soen6441riskgame/views/ExchangeCardView.html{soen6441riskgame.views.ExchangeCardView}]] #white {
}

hide soen6441riskgame.views.ExchangeCardView fields
hide soen6441riskgame.views.ExchangeCardView methods

soen6441riskgame.singleton.GameBoard -->  "exchangeCardView" soen6441riskgame.views.ExchangeCardView

class "<b><size:14>Card</b>\n<size:10>soen6441riskgame.models" as soen6441riskgame.models.Card  [[../../soen6441riskgame/models/Card.html{soen6441riskgame.models.Card}]] #white {
}

hide soen6441riskgame.models.Card fields
hide soen6441riskgame.models.Card methods

soen6441riskgame.singleton.GameBoard -->  "cards" soen6441riskgame.models.Card

class "<b><size:14>PrintStream</b>\n<size:10>java.io" as java.io.PrintStream  #lightgrey {
}

hide java.io.PrintStream fields
hide java.io.PrintStream methods

soen6441riskgame.singleton.GameBoard -->  "standardPrintStream" java.io.PrintStream

interface "<b><size:14>Resettable</b>\n<size:10>soen6441riskgame.singleton" as soen6441riskgame.singleton.Resettable  [[../../soen6441riskgame/singleton/Resettable.html{soen6441riskgame.singleton.Resettable}]] {
}

hide soen6441riskgame.singleton.Resettable fields
hide soen6441riskgame.singleton.Resettable methods

soen6441riskgame.singleton.GameBoard ..|> soen6441riskgame.singleton.Resettable

enum "<b><size:14>CardType</b>\n<size:10>soen6441riskgame.enums" as soen6441riskgame.enums.CardType  [[../../soen6441riskgame/enums/CardType.html{soen6441riskgame.enums.CardType}]] #white {
}

hide soen6441riskgame.enums.CardType fields
hide soen6441riskgame.enums.CardType methods

soen6441riskgame.singleton.GameBoard ..> soen6441riskgame.enums.CardType


@enduml
