@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
package soen6441riskgame.models.strategies [[../../../soen6441riskgame/models/strategies/package-summary.html{soen6441riskgame.models.strategies}]] #lightyellow {
}

class "<b><size:14>AggressiveStrategy</b>" as soen6441riskgame.models.strategies.AggressiveStrategy  [[../../../soen6441riskgame/models/strategies/AggressiveStrategy.html{soen6441riskgame.models.strategies.AggressiveStrategy}]] {
}

hide soen6441riskgame.models.strategies.AggressiveStrategy fields
hide soen6441riskgame.models.strategies.AggressiveStrategy methods

class "<b><size:14>BenevolentStrategy</b>" as soen6441riskgame.models.strategies.BenevolentStrategy  [[../../../soen6441riskgame/models/strategies/BenevolentStrategy.html{soen6441riskgame.models.strategies.BenevolentStrategy}]] {
}

hide soen6441riskgame.models.strategies.BenevolentStrategy fields
hide soen6441riskgame.models.strategies.BenevolentStrategy methods

class "<b><size:14>CheaterStrategy</b>" as soen6441riskgame.models.strategies.CheaterStrategy  [[../../../soen6441riskgame/models/strategies/CheaterStrategy.html{soen6441riskgame.models.strategies.CheaterStrategy}]] {
}

hide soen6441riskgame.models.strategies.CheaterStrategy fields
hide soen6441riskgame.models.strategies.CheaterStrategy methods

class "<b><size:14>HumanStrategy</b>" as soen6441riskgame.models.strategies.HumanStrategy  [[../../../soen6441riskgame/models/strategies/HumanStrategy.html{soen6441riskgame.models.strategies.HumanStrategy}]] {
}

hide soen6441riskgame.models.strategies.HumanStrategy fields
hide soen6441riskgame.models.strategies.HumanStrategy methods

class "<b><size:14>RandomStrategy</b>" as soen6441riskgame.models.strategies.RandomStrategy  [[../../../soen6441riskgame/models/strategies/RandomStrategy.html{soen6441riskgame.models.strategies.RandomStrategy}]] {
}

hide soen6441riskgame.models.strategies.RandomStrategy fields
hide soen6441riskgame.models.strategies.RandomStrategy methods

interface "<b><size:14>Strategy</b>" as soen6441riskgame.models.strategies.Strategy  [[../../../soen6441riskgame/models/strategies/Strategy.html{soen6441riskgame.models.strategies.Strategy}]] {
}

hide soen6441riskgame.models.strategies.Strategy fields
hide soen6441riskgame.models.strategies.Strategy methods

soen6441riskgame.models.strategies.AggressiveStrategy ..|> soen6441riskgame.models.strategies.Strategy
soen6441riskgame.models.strategies.BenevolentStrategy ..|> soen6441riskgame.models.strategies.Strategy
soen6441riskgame.models.strategies.CheaterStrategy ..|> soen6441riskgame.models.strategies.Strategy
soen6441riskgame.models.strategies.HumanStrategy ..|> soen6441riskgame.models.strategies.Strategy
soen6441riskgame.models.strategies.RandomStrategy ..|> soen6441riskgame.models.strategies.Strategy

@enduml
