name: Code Coverage

on: [push]

env:
  global:
    - CODECOV_TOKEN=:${{secrets.CODECOV_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          mvn jacoco:prepare-agent test jacoco:report
      - name: Codecov
        uses: codecov/codecov-action@v1.0.0
