name: Java CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'doc/**'
    - 'grades/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install javafx
      run: |
        sudo apt purge openjfx
        sudo apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
        sudo apt-mark hold openjfx libopenjfx-jni libopenjfx-java
    - name: Build with Maven
      run: |
        mvn package --file pom.xml
        mvn compile
        mvn clean test
